apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-spring-demo
  template:
    metadata:
      labels:
        app: kubernetes-spring-demo
    spec:
      containers:
      - name: kubernetes-spring-demo
        image: basselfaisal/kubernetes-spring-demo
        ports:
        - containerPort: 8080