apiVersion: v1
kind: Service
metadata:
  name: kubernetes-spring-demo
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-spring-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080